### ISSUE TITLE
tailwind class next to a ";" semicolon causing extension not to recognize

### ISSUE THREAD

**Issue by WybeBosch** [yannxaver/tailwind-class-genie#1]
Hey there! 

Loving the extensions so far, i have mini issue when a tailwind class is at the end of a sentence. 

We use tailwind in laravel blade files (index.blade.php) as such
```html
<div class="pr-14"></div>
```

And also inside css files (index.css)
```css
&[aria-expanded='true'] {
	&::before {
		@apply pr-14;
	}
}
```

The extension actually works just fine in css files, but when you try and modify a property at the end of a declaration it has a semicolon next to it. This causes the extension to not recognize the class 

<img width="623" alt="image" src="https://github.com/user-attachments/assets/99a8474d-d327-4f14-87ae-fb46f90d3035">

But if you then put something next to it so its not the last item next to a ";" then the extension works again.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/066a7f3b-abb6-457b-be6b-26ef5bccda93">

Is the edgecase of ";" something that could perhaps be factored into the regex that the extension uses? :)

**Comment by yannxaver** [comment]
Thank you for reporting this. Can you confirm whether the new version fixes the problem?

**Comment by WybeBosch** [comment]
> Thank you for reporting this. Can you confirm whether the new version fixes the problem?

Yes! :D its working great now, thank you for implementing the fix for this so quickly, 
now i can deff recommend the extension to my team aswell! :)

**Comment by yannxaver** [comment]
Glad to hear it's working correctly.
